server {
  listen 80;
  server_name teamup-kg.com www.teamup-kg.com;

  root /usr/share/nginx/html;
  index index.html;


    location /api/ {
    proxy_pass __BACKEND_ORIGIN__/;
    proxy_http_version 1.1;
    proxy_set_header Host $proxy_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_ssl_server_name on;
  }


  location / {
    try_files $uri /index.html;
  }

  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
  }

  location ~* \.(png|jpe?g|webp|svg|gif|ico)$ {
    add_header Cache-Control "public, max-age=86400";
    try_files $uri =404;
  }
}
